config/routes.rb
Rails.application.routes.draw do
  resources :user_jobs
  resources :requirements
  resources :results
  resources :jobs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/index'

  root to: 'home#index'

  get 'users/index'

  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :user_jobs
	def to_s 
		self.job_name
	end
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  belongs_to :job
  
  def to_s 
  	self.requirement
  end

end

app/models/result.rb
class Result < ApplicationRecord
	has_many :user_jobs

	def to_s
		self.result 
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_jobs
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    def to_s 
    	self.name
    end     

end

app/models/user_job.rb
class UserJob < ApplicationRecord
  serialize :users, Array
  serialize :jobs, Array 
  belongs_to :user
  belongs_to :job
  
  belongs_to :result
  belongs_to :requirement
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  		redirect_to users_path
  	end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to @job, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /jobs/1
  def update
    if @job.update(job_params)
      redirect_to @job, notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /jobs/1
  def destroy
    @job.destroy
    redirect_to jobs_url, notice: 'Job was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def job_params
      params.require(:job).permit(:job_link, :job_name, :company_name, :job_description)
    end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  before_action :set_requirement, only: [:show, :edit, :update, :destroy]

  # GET /requirements
  def index
    @requirements = Requirement.all
  end

  # GET /requirements/1
  def show
  end

  # GET /requirements/new
  def new
    @requirement = Requirement.new
  end

  # GET /requirements/1/edit
  def edit
  end

  # POST /requirements
  def create
    @requirement = Requirement.new(requirement_params)

    if @requirement.save
      redirect_to @requirement, notice: 'Requirement was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /requirements/1
  def update
    if @requirement.update(requirement_params)
      redirect_to @requirement, notice: 'Requirement was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /requirements/1
  def destroy
    @requirement.destroy
    redirect_to requirements_url, notice: 'Requirement was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requirement
      @requirement = Requirement.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def requirement_params
      params.require(:requirement).permit(:requirement, :job_id)
    end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  def index
    @results = Result.all
  end

  # GET /results/1
  def show
    @result = Result.find(params[:id])#.order("user_id ASC")
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  def create
    @result = Result.new(result_params)

    if @result.save
      redirect_to @result, notice: 'Result was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /results/1
  def update
    if @result.update(result_params)
      redirect_to @result, notice: 'Result was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /results/1
  def destroy
    @result.destroy
    redirect_to results_url, notice: 'Result was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def result_params
      params.require(:result).permit(:result)
    end
end

app/controllers/user_jobs_controller.rb
class UserJobsController < ApplicationController
  before_action :set_user_job, only: [:show, :edit, :update, :destroy]

  # GET /user_jobs
  def index
    @user_jobs = UserJob.all.order("user_id ASC")
  end

  # GET /user_jobs/1
  def show
  end

  # GET /user_jobs/new
  def new
    @user_job = UserJob.new
  end

  # GET /user_jobs/1/edit
  def edit
  end

  # POST /user_jobs
  def create
    @user_job = UserJob.new(user_job_params)
    #UserMailer.jobs(@user_job).deliver
    if @user_job.save
      redirect_to @user_job, notice: 'User job was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /user_jobs/1
  def update
    if @user_job.update(user_job_params)
      redirect_to @user_job, notice: 'User job was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /user_jobs/1
  def destroy
    @user_job.destroy
    redirect_to user_jobs_url, notice: 'User job was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_job
      @user_job = UserJob.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_job_params
      params.require(:user_job).permit(:user_id, :job_id, :result_id, :applied, :interview, :shortlist, :final, :reason, :requirement_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to users_path, :alert => "Access denied."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/user_jobs_helper.rb
module UserJobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<p>Please <%= link_to 'Sign in', new_user_session_path %> or
   <%= link_to 'Sign up', new_user_registration_path %> to continue.</p>

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :job_link %>
    <%= f.input :job_name %>
    <%= f.input :company_name %>
    <%= f.input :job_description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Job name</th>
      <th>Job link</th>
      <th>Company name</th>
      <th>Job description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.job_name %></td>
        <td><a href="<%= job.job_link %>"><%= job.job_link %></a></td>
        <td><%= job.company_name %></td>
        <td><%= job.job_description %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job link:</strong>
  <%= @job.job_link %>
</p>

<p>
  <strong>Job name:</strong>
  <%= @job.job_name %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @job.company_name %>
</p>

<p>
  <strong>Job description:</strong>
  <%= @job.job_description %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/requirements/_form.html.erb
<%= simple_form_for(@requirement) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :requirement %>
    <%= f.association :job %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/requirements/edit.html.erb
<h1>Editing Requirement</h1>

<%= render 'form', requirement: @requirement %>

<%= link_to 'Show', @requirement %> |
<%= link_to 'Back', requirements_path %>

app/views/requirements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requirements</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Requirement</th>
      <th>Job</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requirements.each do |requirement| %>
      <tr>
        <td><%= requirement.requirement %></td>
        <td><%= requirement.job %></td>
        <td><%= link_to 'Show', requirement %></td>
        <td><%= link_to 'Edit', edit_requirement_path(requirement) %></td>
        <td><%= link_to 'Destroy', requirement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Requirement', new_requirement_path %>

app/views/requirements/new.html.erb
<h1>New Requirement</h1>

<%= render 'form', requirement: @requirement %>

<%= link_to 'Back', requirements_path %>

app/views/requirements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requirement:</strong>
  <%= @requirement.requirement %>
</p>

<p>
  <strong>Job:</strong>
  <%= @requirement.job %>
</p>

<%= link_to 'Edit', edit_requirement_path(@requirement) %> |
<%= link_to 'Back', requirements_path %>

app/views/results/_form.html.erb
<%= simple_form_for(@result) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :result %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.result %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<!--  -->
<h1>Successful</h1>
<%= @result.user_jobs.each do |result| %>
	 <div class="panel panel-default">
		 <div class="panel-body">
		 	<td><%= result.id %> | </td>
		 	<td><%= result.user %> | </td>
		 	<td><%= result.result %> | </td>
		 	<td><%= result.job %> | </td>
		 	<td><%= result.applied %> </td>
		 	<td><%= link_to 'Show', result %></td>
        	<td><%= link_to 'Edit', edit_user_job_path(result) %></td>
        	<td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		 </div>
	 </div>

<% end %>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', :back %>

app/views/user_jobs/_form.html.erb
<%= simple_form_for(@user_job) do |f| %>
  <%= f.error_notification %>
  
  <% if @user_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_job.errors.count, "error") %> prohibited this user_job from being saved:</h2>
      <ul>
      <% @user_job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.association :user, input_html: { multiple: true } %> <!-- , input_html: { multiple: true } -->
    <%= f.association :job %>
    <%= f.association :result %>
    <%= f.association :requirement %>
    <%= f.input :applied %>
    <%= f.input :interview %>
    <%= f.input :shortlist %>
    <%= f.input :final %>
    <%= f.input :reason %>
  
  </div>  
    

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_jobs/edit.html.erb
<h1>Editing User Job</h1>

<%= render 'form', user_job: @user_job %>

<%= link_to 'Show', @user_job %> |
<%= link_to 'Back', user_jobs_path %>

app/views/user_jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Jobs</h1>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Job</th>
      <th>Result</th>
      <th>Requirement</th>
      <th>Applied</th>
      <th>Interview</th>
      <th>Shortlist</th>
      <th>Final</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_jobs.each do |user_job| %>
      <tr>
        <td><%= user_job.user %></td>
        <td><%= user_job.job %></td>
        <td><%= user_job.result %></td>
        <td><%= user_job.requirement %></td>
        <td><%= user_job.applied %></td>
        <td><%= user_job.interview %></td>
        <td><%= user_job.shortlist %></td>
        <td><%= user_job.final %></td>
        <td><%= user_job.reason %></td>
        <td><%= link_to 'Show', user_job %></td>
        <td><%= link_to 'Edit', edit_user_job_path(user_job) %></td>
        <td><%= link_to 'Destroy', user_job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Job', new_user_job_path %>

app/views/user_jobs/new.html.erb
<h1>New User Job</h1>

<%= render 'form', user_job: @user_job %>

<%= link_to 'Back', user_jobs_path %>

app/views/user_jobs/show.html.erb
<p>
  <strong>User:</strong>
  <%= @user_job.user %>
</p>

<p>
  <strong>Job:</strong>
  <%= @user_job.job %>
</p>

<p>
  <strong>Result:</strong>
  <%= @user_job.result %>
</p>

<p>
  <strong>Requirement:</strong>
  <%= @user_job.requirement %>
</p>

<p>
  <strong>Applied:</strong>
  <%= @user_job.applied %>
</p>

<p>
  <strong>Interview:</strong>
  <%= @user_job.interview %>
</p>

<p>
  <strong>Shortlist:</strong>
  <%= @user_job.shortlist %>
</p>

<p>
  <strong>Final:</strong>
  <%= @user_job.final %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @user_job.reason %>
</p>

<%= link_to 'Edit', edit_user_job_path(@user_job) %> |
<%= link_to 'View All', user_jobs_path %> |
<%= link_to 'Back', :back %>

app/views/users/index.html.erb
<h1>Users(<%= @users.count %>)</h1>

<% @users.each do |user| %>
	<div class="well" style="padding-top: 15px; padding-bottom: 35px;">
		<div class="col-xs-10 col-md-10">
			<%= user.name %> <%= user.surname %> |
			<%= user.email %>
		</div>
		<div class="col-xs-2 col-md-2">
			<%= link_to "View", user, class: "btn btn-info btn-xs" %>
		</div>
	</div>
<% end %>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Surname: <%= @user.surname if @user.surname %></p>
<p>Email: <%= @user.email if @user.email %></p>